dist: trusty
language: node_js
node_js:
  - "4.3"
compiler: clang-3.8
env:
  matrix:
    - AUTH_SERVER__DATABASE__HOST=127.0.0.1 AUTH_SERVER__DATABASE__PORT=5432 AUTH_SERVER__DATABASE__DATABASE=auth_server_test AUTH_SERVER__DATABASE__USERNAME=postgres AUTH_SERVER__DATABASE__PASSWORD=
  global:
    - LLVM_VERSION=3.8.0
    - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz
    - CXX=$HOME/clang-$LLVM_VERSION/bin/clang++
    - CPPFLAGS="-I $HOME/clang-$LLVM_VERSION/include/c++/v1"
    - CXXFLAGS=-lc++
    - LD_LIBRARY_PATH=$HOME/clang-$LLVM_VERSION/lib:$LD_LIBRARY_PATH
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
   - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
   - mkdir $HOME/clang-$LLVM_VERSION
   - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang-$LLVM_VERSION --strip-components 1

services:
  - "postgresql"

before_script:
  - psql -c 'create database auth_server_test;' -U postgres
